server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always
    schema: classpath:/schema.sql
    data: classpath:/data.sql
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true